version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb+srv://RishabhAgarwal:V7e71O4jtrYm4wnm@atlascluster.kdlq5jz.mongodb.net/ProductService?retryWrites=true&w=majority
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
